#元组是python的内置数据结构，是不可变序列
#'常见不可变序列'（字符串，元组）
a='hello'
print((id(a)))
a=a+'world'
print((id(a)))
print(a)
#第一种创建方式和列表相似，只不过元组使用(),小括号可以省略，并且只含一个元素的元组需要使用逗号和小括号。
b='a',48,'c','d'
print(b)
print(type(b))
#第二种创建方式，使用tuple()
c=tuple(('1','a',48,'wrnd'))
print(c)
print(type(c))

t=(10,[10,100,1000],'lbw')
print(t)
print(type(t))
print(t[0],t[1],t[2])
print(type(t[0]),type(t[1]),type(t[2]))
'''由于列表是可变序列，所以可以向列表中添加元素，而列表的内存地址不变'''
t[1].append(999)
print(t)
